package com.jessica.happybrain

object PreguntasData {

    val espanolBasico = listOf(
        Pregunta("¿Qué es un sustantivo?", listOf("Una acción", "El nombre de una persona, animal o cosa", "Una descripción"), 1),
        Pregunta("¿Cuál de las siguientes palabras es un adjetivo?", listOf("Correr", "Bonito", "Ella"), 1),
        Pregunta("¿Qué es un verbo?", listOf("Un objeto", "Una emoción", "Una palabra que indica accion"), 2),
        Pregunta("¿Cuál es el plural de casa?", listOf("Cases", "Casas", "Casos"), 1),
        Pregunta("¿Cuál palabra está bien escrita?", listOf("Hueso", "Güeso", "Ueso"), 0),
        Pregunta("¿Qué signo se usa al hacer una pregunta?", listOf("Coma", "Signo de interrogacion", "Punto"), 1),
        Pregunta("¿Qué es una oración?", listOf("Una palabra", "Un sonido", "Un conjunto de palabras con sentido completo"), 2),
        Pregunta("¿Cuál palabra rima con sol?", listOf("Luna", "Col", "Libro"), 1),
        Pregunta("¿Qué palabra está mal escrita?", listOf("Ezcuela", "Escuela", "Cuaderno"), 0),
        Pregunta("¿Cuál palabra es un pronombre?", listOf("Azul", "Nosotros", "Comer"), 1),
        Pregunta("¿Qué es un antónimo?", listOf("Una palabra parecida", "Una palabra que rima", "Una palabra con significado opuesto"), 2),
        Pregunta("¿Cuál es el sinónimo de bonito?", listOf("Hermoso", "Feo", "Lento"), 0),
        Pregunta("¿Qué es un cuento?", listOf("Un número", "Una narracion breve y ficticia", "Una lista de palabras"), 1),
        Pregunta("¿Qué palabra es un sustantivo?", listOf("Saltar", "Feliz", "Mesa"), 2),
        Pregunta("¿Cuál de estas palabras es un verbo?", listOf("Azul", "Manzana", "Correr"), 2),
        Pregunta("¿Cuál palabra no pertenece al grupo?", listOf("Libro", "Cuaderno", "Correr"), 2),
        Pregunta("¿Cuál palabra está escrita con mayúscula correctamente?", listOf("México", "mexico", "méxico"), 0),
        Pregunta("¿Qué palabra es un adjetivo calificativo?", listOf("Mesa", "Saltar", "Grande"), 2),
        Pregunta("¿Cuál es el artículo definido en la oración “El niño juega”?", listOf("El", "Niño", "Juega"), 0),
        Pregunta("¿Qué es una sílaba?", listOf("Una letra", "Una oración", "Un sonido o grupo de sonidos que se pronuncian en un solo golpe de voz"), 2)
    )

    val espanolMedio = listOf(
        Pregunta("¿Qué es un sustantivo abstracto?", listOf("Algo que se puede tocar", "Algo que no se puede tocar, como una emoción", "Un color"), 1),
        Pregunta("¿Cuál es un ejemplo de verbo en infinitivo?", listOf("Corre", "Comer", "Comió"), 1),
        Pregunta("¿Qué función tiene el sujeto en una oración?", listOf("Realizar la acción", "Indicar de quién se habla en la oración", "Mostrar emociones"), 1),
        Pregunta("¿Cuál de las siguientes oraciones tiene adjetivo?", listOf("El niño corre", "La flor roja es bonita", "Ellos juegan"), 1),
        Pregunta("¿Qué palabra es sinónimo de 'rápido'?", listOf("Lento", "Tarde", "Veloz"), 2),
        Pregunta("¿Cuál oración tiene un error de ortografía?", listOf("Yo beo la tele", "Ella canta muy bien", "Nosotros comemos"), 0),
        Pregunta("¿Qué es un párrafo?", listOf("Una palabra larga", "Una oración", "Un conjunto de oraciones que desarrollan una idea"), 2),
        Pregunta("¿Qué tipo de texto es una noticia?", listOf("Literario", "Informativo", "Instructivo"), 1),
        Pregunta("¿Qué es una metáfora?", listOf("Una comparación con 'como'", "Decir algo usando otra imagen o idea", "Una rima"), 1),
        Pregunta("¿Cuál es el modo verbal de la oración 'Yo quisiera ir'?", listOf("Indicativo", "Subjuntivo", "Imperativo"), 1),
        Pregunta("¿Qué palabra es un conector lógico?", listOf("Sin embargo", "Silla", "Correr"), 0),
        Pregunta("¿Cuál de estas oraciones está en futuro?", listOf("Juan juega fútbol", "Juan jugó fútbol", "Juan jugará fútbol"), 2),
        Pregunta("¿Cuál es un ejemplo de sustantivo colectivo?", listOf("Pescado", "Cardumen", "Agua"), 1),
        Pregunta("¿Qué es una antología?", listOf("Una persona que analiza cuentos", "Un libro de matemáticas", "Una recopilación de textos literarios"), 2),
        Pregunta("¿Cuál palabra está escrita con tilde correctamente?", listOf("Cafetería", "Pájaro", "Libros"), 1),
        Pregunta("¿Qué es una oración compuesta?", listOf("Una oración con un verbo", "Una oración que tiene dos o más verbos unidos por un nexo", "Una exclamación"), 1),
        Pregunta("¿Cuál es el pronombre adecuado para 'María y yo'?", listOf("Nosotros", "Ellos", "Tú"), 0),
        Pregunta("¿Cuál palabra funciona como preposición?", listOf("Alegre", "Saltar", "Sobre"), 2),
        Pregunta("¿Cuál palabra es aguda y lleva tilde?", listOf("Mesa", "Joven", "Café"), 2),
        Pregunta("¿Cuál oración es imperativa?", listOf("Yo como arroz", "Limpia tu cuarto ahora", "Él corre rápido"), 1)
    )

    val espanolAvanzado = listOf(
        Pregunta("¿Qué es una perífrasis verbal?", listOf("Una palabra compuesta", "Una construcción con dos o más verbos que funcionan como uno solo", "Un tipo de sustantivo"), 1),
        Pregunta("¿Cuál de estas oraciones está en voz pasiva?", listOf("El perro comió la carne", "La carne fue comida por el perro", "El perro corre"), 1),
        Pregunta("¿Qué función tiene el complemento directo?", listOf("Indicar lugar", "Recibir directamente la acción del verbo", "Unir palabras"), 1),
        Pregunta("¿Cuál es un ejemplo de oración subordinada?", listOf("Me alegra que vengas a verme", "Yo comí pizza", "Ellos estudian"), 0),
        Pregunta("¿Qué tipo de texto es una crónica?", listOf("Científico", "Narrativo y periodístico", "Poético"), 1),
        Pregunta("¿Qué es el hiato?", listOf("La unión de dos vocales que se separan en sílabas distintas", "Una interrupción entre vocales fuertes o tilde en vocal débil", "Una mezcla de consonantes"), 0),
        Pregunta("¿Cuál es un ejemplo de lenguaje figurado?", listOf("Estoy cansado", "Tengo mariposas en el estómago", "Comí arroz"), 1),
        Pregunta("¿Qué es una figura retórica?", listOf("Un tipo de verbo", "Un adjetivo especial", "Una forma de embellecer el lenguaje"), 2),
        Pregunta("¿Cuál es una característica del ensayo?", listOf("Es 100% objetivo", "Expone ideas y argumentos del autor", "Es completamente ficticio"), 1),
        Pregunta("¿Qué es un texto argumentativo?", listOf("El que narra una historia", "El que defiende una idea con razones", "El que da instrucciones"), 1),
        Pregunta("¿Qué es una anáfora?", listOf("Una metáfora en negativo", "La repetición de una palabra al inicio de varios versos u oraciones", "Un conector de causa"), 1),
        Pregunta("¿Qué palabra es un gerundio?", listOf("Comer", "Comiendo", "Comido"), 1),
        Pregunta("¿Cuál es un ejemplo de oración exclamativa?", listOf("El sol está brillando", "Quiero helado", "Qué hermoso día"), 2),
        Pregunta("¿Qué es una prosopopeya?", listOf("Una figura en matemáticas", "Atribuir cualidades humanas a cosas o animales", "Un error de escritura"), 1),
        Pregunta("¿Cuál oración está escrita en pretérito pluscuamperfecto?", listOf("Yo caminaba", "Yo había salido temprano", "Yo salgo"), 1),
        Pregunta("¿Qué es un caligrama?", listOf("Un párrafo sin sentido", "Una carta formal", "Un poema con forma de dibujo"), 2),
        Pregunta("¿Qué es un silogismo?", listOf("Una exclamación", "Una forma de razonamiento lógico", "Una metáfora"), 1),
        Pregunta("¿Cuál oración está escrita en forma impersonal?", listOf("Yo hice la tarea", "Se dice que va a llover", "Ella corre rápido"), 1),
        Pregunta("¿Qué tipo de palabra es 'rápidamente'?", listOf("Sustantivo", "Adjetivo", "Adverbio de modo"), 2),
        Pregunta("¿Cuál es la función del texto instructivo?", listOf("Indicar pasos para realizar una actividad", "Contar una historia", "Describir un lugar"), 0)
    )

    val matematicasBasico = listOf(
        Pregunta("¿Cuánto es 5 + 3?", listOf("A) 7", "B) 8", "C) 9"), 1),
        Pregunta("¿Cuánto es 10 – 4?", listOf("A) 6", "B) 5", "C) 4"), 0),
        Pregunta("¿Cuál es el valor de 6 × 7?", listOf("A) 42", "B) 36", "C) 30"), 0),
        Pregunta("¿Cuánto es 16 ÷ 4?", listOf("A) 4", "B) 3", "C) 5"), 0),
        Pregunta("Si tienes 3 manzanas y compras 2 más, ¿cuántas manzanas tienes en total?", listOf("A) 4", "B) 5", "C) 6"), 1),
        Pregunta("¿Qué número falta en la secuencia 2, 4, 6, ___, 10?", listOf("A) 7", "B) 8", "C) 9"), 1),
        Pregunta("¿Cuál es el número que sigue en la secuencia 1, 3, 5, 7, ___?", listOf("A) 8", "B) 9", "C) 6"), 1),
        Pregunta("Si sumas 12 + 5, ¿qué número obtienes?", listOf("A) 18", "B) 17", "C) 16"), 1),
        Pregunta("¿Cuánto es 8 × 5?", listOf("A) 35", "B) 40", "C) 45"), 1),
        Pregunta("¿Cuánto es 20 ÷ 5?", listOf("A) 3", "B) 5", "C) 4"), 2),
        Pregunta("¿Cuánto es 9 + 4?", listOf("A) 11", "B) 13", "C) 12"), 1),
        Pregunta("¿Cuál es el valor de 2 × 10?", listOf("A) 20", "B) 18", "C) 12"), 0),
        Pregunta("¿Qué número falta en la secuencia 5, 10, 15, ___, 25?", listOf("A) 18", "B) 20", "C) 22"), 1),
        Pregunta("¿Qué número es más grande, 15 o 18?", listOf("A) 15", "B) 18", "C) Son iguales"), 1),
        Pregunta("Si tienes 10 caramelos y le das 3 a tu amigo, ¿cuántos te quedan?", listOf("A) 6", "B) 7", "C) 8"), 1),
        Pregunta("Si 3 × 2 = 6, ¿cuál es el resultado de 6 ÷ 2?", listOf("A) 3", "B) 4", "C) 2"), 0),
        Pregunta("¿Cuánto es 18 ÷ 2?", listOf("A) 8", "B) 9", "C) 10"), 1),
        Pregunta("¿Qué número falta en la secuencia 10, 20, 30, ___, 50?", listOf("A) 40", "B) 35", "C) 45"), 0),
        Pregunta("¿Cuánto es 6 × 3?", listOf("A) 18", "B) 15", "C) 20"), 0),
        Pregunta("¿Cuál es el resultado de 4 × 5?", listOf("A) 15", "B) 20", "C) 10"), 1)
    )

    val matematicasMedio = listOf(
        Pregunta("¿Cuánto es 25 × 4?", listOf("A) 100", "B) 80", "C) 90"), 1),
        Pregunta("Si tienes 50 galletas y las repartes entre 5 amigos, ¿cuántas galletas recibe cada uno?", listOf("A) 10", "B) 9", "C) 12"), 0),
        Pregunta("¿Cuál es el área de un cuadrado de 6 cm de lado?", listOf("A) 12 cm²", "B) 36 cm²", "C) 24 cm²"), 1),
        Pregunta("¿Cuánto es 15 ÷ 3?", listOf("A) 3", "B) 5", "C) 6"), 1),
        Pregunta("Si tienes 12 manzanas y las repartes entre 3 personas, ¿cuántas manzanas recibe cada persona?", listOf("A) 3", "B) 4", "C) 5"), 1),
        Pregunta("¿Qué número es el doble de 18?", listOf("A) 34", "B) 36", "C) 40"), 1),
        Pregunta("¿Cuánto es 9 × 7?", listOf("A) 63", "B) 72", "C) 56"), 0),
        Pregunta("¿Cuál es el perímetro de un rectángulo con lados de 8 cm y 5 cm?", listOf("A) 26 cm", "B) 30 cm", "C) 40 cm"), 0),
        Pregunta("¿Qué número es la mitad de 50?", listOf("A) 25", "B) 30", "C) 15"), 0),
        Pregunta("¿Cuánto es 8³?", listOf("A) 512", "B) 216", "C) 64"), 1),
        Pregunta("Si una camisa cuesta $200 y tiene un descuento del 25%, ¿cuál es su precio final?", listOf("A) $150", "B) $175", "C) $180"), 0),
        Pregunta("¿Cuál es el valor de la raíz cuadrada de 64?", listOf("A) 8", "B) 10", "C) 12"), 0),
        Pregunta("Si el perímetro de un triángulo equilátero es 24 cm, ¿cuánto mide cada lado?", listOf("A) 6 cm", "B) 8 cm", "C) 10 cm"), 0),
        Pregunta("¿Cuánto es 12 × 9?", listOf("A) 108", "B) 96", "C) 105"), 0),
        Pregunta("¿Cuál es el volumen de un cubo con lados de 4 cm?", listOf("A) 16 cm³", "B) 32 cm³", "C) 64 cm³"), 2),
        Pregunta("Si el radio de un círculo es 7 cm, ¿cuál es su área (usa π = 3.14)?", listOf("A) 153.86 cm²", "B) 154 cm²", "C) 143.38 cm²"), 0),
        Pregunta("¿Cuánto es 20 ÷ 4 + 6?", listOf("A) 11", "B) 9", "C) 12"), 0),
        Pregunta("Si una pizza tiene 8 partes y comes 3, ¿qué fracción de la pizza has comido?", listOf("A) 3/8", "B) 5/8", "C) 2/8"), 0),
        Pregunta("¿Cuánto es 16 ÷ 2 × 4?", listOf("A) 32", "B) 28", "C) 20"), 0),
        Pregunta("Si tienes 2/3 de una torta y la compartes con un amigo, ¿cuánto le das?", listOf("A) 1/3", "B) 2/3", "C) 1/2"), 0)
    )

    val matematicasAvanzado = listOf(
        Pregunta("¿Cuál es el valor de π (pi)?", listOf("A) 3.14", "B) 3.1416", "C) 3.13"), 1),
        Pregunta("¿Cuánto es 3² + 4²?", listOf("A) 25", "B) 16", "C) 20"), 0),
        Pregunta("Resuelve la ecuación: 2x + 5 = 15", listOf("A) 7", "B) 5", "C) 10"), 0),
        Pregunta("Si x = 4, ¿cuál es el valor de 3x + 2?", listOf("A) 14", "B) 16", "C) 12"), 0),
        Pregunta("¿Cuánto es 5! (factorial de 5)?", listOf("A) 120", "B) 100", "C) 60"), 0),
        Pregunta("¿Cuál es la derivada de x²?", listOf("A) 2x", "B) x", "C) x²"), 0),
        Pregunta("Si un círculo tiene radio 10 cm, ¿cuál es su circunferencia (usa π = 3.14)?", listOf("A) 31.4 cm", "B) 62.8 cm", "C) 20 cm"), 0),
        Pregunta("¿Qué es el logaritmo en base 10 de 100?", listOf("A) 2", "B) 3", "C) 1"), 0),
        Pregunta("Resuelve la ecuación: x² – 4 = 0", listOf("A) 2", "B) 4", "C) 0"), 0),
        Pregunta("¿Cuánto es la integral de x dx?", listOf("A) x²/2", "B) x³/3", "C) x²"), 0),
        Pregunta("¿Cuál es el valor de la constante de Euler (e)?", listOf("A) 2.71", "B) 3.14", "C) 1.61"), 0),
        Pregunta("Si tienes una ecuación cuadrática de la forma ax² + bx + c = 0, ¿cuál es la fórmula general para encontrar sus raíces?", listOf("A) x = (-b ± √(b²-4ac)) / 2a", "B) x = b ± √(a²+bc) / a", "C) x = (-b ± √(a²-4ac)) / 2b"), 0),
        Pregunta("¿Cuál es la derivada de sen(x)?", listOf("A) cos(x)", "B) -cos(x)", "C) sin(x)"), 0),
        Pregunta("¿Cuánto es la raíz cuadrada de 81?", listOf("A) 9", "B) 8", "C) 7"), 0),
        Pregunta("¿Cuál es el valor de la integral de 1/x dx?", listOf("A) ln|x|", "B) x", "C) 1/x²"), 0),
        Pregunta("¿Cuál es el valor de la constante de Planck?", listOf("A) 6.626 x 10^-34 J·s", "B) 6.022 x 10^-23 J·s", "C) 9.81 m/s²"), 0),
        Pregunta("¿Qué representa la fórmula de Euler e^(iπ) + 1 = 0?", listOf("A) Una identidad matemática fundamental", "B) Una fórmula de física", "C) Una ecuación de álgebra"), 0),
        Pregunta("¿Cuál es el límite de (1/x) cuando x tiende a infinito?", listOf("A) 0", "B) 1", "C) ∞"), 0)
    )

    val historiaBasico = listOf(
        Pregunta("¿Quién fue el primer presidente de México?", listOf("Miguel Hidalgo", "Guadalupe Victoria", "Benito Juárez"), 1),
        Pregunta("¿En qué año comenzó la Independencia de México?", listOf("1821", "1810", "1847"), 1),
        Pregunta("¿Qué personaje histórico dio el Grito de Dolores?", listOf("Emiliano Zapata", "Miguel Hidalgo", "Francisco Villa"), 1),
        Pregunta("¿Qué día se celebra la Independencia de México?", listOf("15 de agosto", "20 de noviembre", "16 de septiembre"), 2),
        Pregunta("¿Qué civilización construyó Chichén Itzá?", listOf("Azteca", "Olmeca", "Maya"), 2),
        Pregunta("¿Cuál fue la última gran civilización prehispánica en México?", listOf("Olmeca", "Zapoteca", "Mexica (Azteca)"), 2),
        Pregunta("¿Quién fue Benito Juárez?", listOf("Un revolucionario", "Un presidente liberal y reformista", "Un emperador"), 1),
        Pregunta("¿Qué país conquistó a los aztecas?", listOf("Inglaterra", "España", "Francia"), 1),
        Pregunta("¿Qué fueron los Tlatoanis?", listOf("Dioses aztecas", "Gobernantes mexicas", "Guerreros mayas"), 1),
        Pregunta("¿Qué civilización prehispánica usó el calendario solar y lunar?", listOf("Maya", "Tolteca", "Mexica"), 0),
        Pregunta("¿Quién fue el emperador mexica durante la llegada de los españoles?", listOf("Moctezuma II", "Cuauhtémoc", "Itzcóatl"), 0),
        Pregunta("¿Qué representa el 5 de mayo en México?", listOf("La Batalla de Puebla", "La Independencia", "El fin de la Revolución"), 0),
        Pregunta("¿Qué es una pirámide en el contexto prehispánico?", listOf("Una tumba moderna", "Un templo religioso", "Una cárcel"), 1),
        Pregunta("¿Cuál fue una causa de la Revolución Mexicana?", listOf("Descubrimiento de América", "Desigualdad social y dictadura de Porfirio Díaz", "Fin de la monarquía"), 1),
        Pregunta("¿Qué hizo Lázaro Cárdenas?", listOf("Fundó Tenochtitlan", "Luchó en la Independencia", "Expropió el petróleo"), 2),
        Pregunta("¿Qué civilización fue conocida por sus cabezas colosales de piedra?", listOf("Maya", "Olmeca", "Mexica"), 1),
        Pregunta("¿Qué fue la Nueva España?", listOf("Una ciudad antigua", "El nombre de México durante la colonización española", "Una guerra"), 1),
        Pregunta("¿Quién fue el último emperador mexica?", listOf("Moctezuma I", "Nezahualcóyotl", "Cuauhtémoc"), 2),
        Pregunta("¿Qué eran los códices prehispánicos?", listOf("Espadas", "Libros antiguos hechos con dibujos y símbolos", "Lenguas"), 1),
        Pregunta("¿Cuál país invadió México en la Intervención de 1862?", listOf("Estados Unidos", "Francia", "Alemania"), 1)
    )

    val historiaMedio = listOf(
        Pregunta("¿Qué fue la Conquista de México?", listOf("Un tratado de paz", "El proceso por el cual los españoles dominaron a los pueblos indígenas", "Una guerra entre mayas y aztecas"), 1),
        Pregunta("¿Quién lideró la expedición española que conquistó Tenochtitlan?", listOf("Cristóbal Colón", "Hernán Cortés", "Simón Bolívar"), 1),
        Pregunta("¿Qué importante ciudad fundaron los mexicas?", listOf("Palenque", "Teotihuacán", "Tenochtitlan"), 2),
        Pregunta("¿Qué fue la encomienda?", listOf("Una ley para construir escuelas", "Un sistema donde los españoles recibían indígenas para trabajar", "Un templo ceremonial"), 1),
        Pregunta("¿Quién escribió los “Sentimientos de la Nación”?", listOf("Miguel Hidalgo", "José María Morelos", "Ignacio Allende"), 1),
        Pregunta("¿Qué eran los criollos en la época colonial?", listOf("Hijos de españoles nacidos en América", "Españoles que vivían en Europa", "Indígenas aliados"), 0),
        Pregunta("¿Qué país ayudó a México en su independencia?", listOf("Francia", "Inglaterra", "Estados Unidos"), 2),
        Pregunta("¿Qué es el Porfiriato?", listOf("La guerra entre Porfirio Díaz y Juárez", "El periodo en que Porfirio Díaz fue presidente de México por más de 30 años", "Una revolución indígena"), 1),
        Pregunta("¿Qué ocurrió en 1821 en México?", listOf("Se firmó la Constitución", "Se logró la Independencia", "Se fundó la UNAM"), 1),
        Pregunta("¿Qué fue la Reforma?", listOf("Una guerra internacional", "Un movimiento para separar Iglesia y Estado en México", "Una invasión"), 1),
        Pregunta("¿Qué personaje fue clave en las Leyes de Reforma?", listOf("Porfirio Díaz", "Agustín de Iturbide", "Benito Juárez"), 2),
        Pregunta("¿Qué fue la Constitución de 1857?", listOf("Un tratado con Francia", "Una nueva ley fundamental liberal en México", "Un reglamento colonial"), 1),
        Pregunta("¿Qué guerra enfrentó México contra Estados Unidos en 1846?", listOf("La Revolución", "La Guerra de Intervención", "La de Independencia"), 1),
        Pregunta("¿Qué territorios perdió México en esa guerra?", listOf("Yucatán y Tabasco", "Texas, California, Arizona, entre otros", "Chiapas y Oaxaca"), 1),
        Pregunta("¿Quién fue el primer emperador de México después de la independencia?", listOf("Benito Juárez", "Agustín de Iturbide", "Vicente Guerrero"), 1),
        Pregunta("¿Qué conflicto se conmemora el 20 de noviembre?", listOf("La Conquista", "El inicio de la Revolución Mexicana", "La fundación de Tenochtitlan"), 1),
        Pregunta("¿Qué fue el Plan de Ayala?", listOf("Un proyecto educativo", "Un tratado con Francia", "Un documento de Emiliano Zapata en contra de Madero"), 2),
        Pregunta("¿Qué buscaban los caudillos revolucionarios?", listOf("La colonización", "Una monarquía", "Justicia social y reforma agraria"), 2),
        Pregunta("¿Quién fue Francisco I. Madero?", listOf("Un sacerdote", "Un líder revolucionario que luchó contra Porfirio Díaz", "Un explorador"), 1),
        Pregunta("¿Qué fue la Constitución de 1917?", listOf("Una carta colonial", "La ley suprema de México tras la Revolución, aún vigente hoy", "Un tratado con EUA"), 1)
    )

    val historiaAvanzado = listOf(
        Pregunta("¿Cuál fue la principal causa de la caída de Tenochtitlan?", listOf("El mal clima", "El abandono mexica", "La alianza entre los españoles y otros pueblos indígenas"), 2),
        Pregunta("¿Qué fue la Noche Triste?", listOf("El incendio de Tenochtitlan", "La derrota de los españoles al intentar huir de Tenochtitlan", "La muerte de Moctezuma"), 1),
        Pregunta("¿Qué tratado marcó el fin de la Guerra de Independencia de México?", listOf("Tratado de Guadalupe Hidalgo", "Tratados de Córdoba", "Plan de Ayala"), 1),
        Pregunta("¿Quién fue la emperatriz durante el Segundo Imperio Mexicano?", listOf("Carlota de Austria", "Carlota de Bélgica", "Carlota de España"), 0),
        Pregunta("¿Qué país impuso a Maximiliano de Habsburgo como emperador de México?", listOf("España", "Inglaterra", "Francia"), 2),
        Pregunta("¿Qué personaje fue fusilado en el Cerro de las Campanas?", listOf("Benito Juárez", "Maximiliano de Habsburgo", "Porfirio Díaz"), 1),
        Pregunta("¿Qué fue el movimiento cristero?", listOf("Una rebelión indígena", "Un conflicto armado por la defensa religiosa contra el gobierno mexicano", "Una invasión extranjera"), 1),
        Pregunta("¿Qué grupo impulsó las reformas agrarias durante la Revolución Mexicana?", listOf("Los conservadores", "Los zapatistas", "Los científicos"), 1),
        Pregunta("¿Qué político fundó el PRI (Partido Revolucionario Institucional)?", listOf("Benito Juárez", "Plutarco Elías Calles", "Lázaro Cárdenas"), 1),
        Pregunta("¿Qué ocurrió durante la Matanza de Tlatelolco en 1968?", listOf("Un terremoto", "Una invasión extranjera", "Un ataque militar contra estudiantes manifestantes"), 2),
        Pregunta("¿Qué evento permitió el regreso de los Borbones a España en el siglo XIX y afectó a la Nueva España?", listOf("La invasión napoleónica", "La Revolución Francesa", "La guerra contra Inglaterra"), 0),
        Pregunta("¿Qué hizo Miguel Lerdo de Tejada con respecto a las tierras?", listOf("Creó más latifundios", "Expropió tierras del clero", "Las vendió a Francia"), 1),
        Pregunta("¿Qué evento marcó el inicio del Porfiriato?", listOf("El triunfo de Juárez", "El Plan de Tuxtepec", "La Reforma Agraria"), 1),
        Pregunta("¿Qué fue el Plan de San Luis?", listOf("Un llamado de Madero para derrocar a Porfirio Díaz", "Una ley de comercio", "Un tratado internacional"), 0),
        Pregunta("¿Qué fue la Constitución de Apatzingán?", listOf("Una carta escrita por Juárez", "La primera constitución mexicana, hecha por los insurgentes", "Un documento colonial"), 1),
        Pregunta("¿Quién lideró la defensa de Chapultepec en 1847?", listOf("Emiliano Zapata", "Los Niños Héroes", "José María Morelos"), 1),
        Pregunta("¿Qué territorio mexicano fue anexionado por EUA antes de la guerra?", listOf("Texas", "Baja California", "Yucatán"), 0),
        Pregunta("¿Qué fue el Maximato?", listOf("Un imperio", "El periodo en que Calles controló a los presidentes sin serlo", "Un tratado"), 1),
        Pregunta("¿Qué presidente nacionalizó la industria petrolera?", listOf("Porfirio Díaz", "Lázaro Cárdenas", "Francisco I. Madero"), 1),
        Pregunta("¿Cuál fue el papel de José Vasconcelos en la historia mexicana?", listOf("Fundó el Banco de México", "Impulsó la educación pública y la cultura", "Firmó la independencia"), 1)
    )

    val curiosidadesBasico = listOf(
        Pregunta("¿Cuál es el planeta más cercano al sol?", listOf("A) Venus", "B) Mercurio", "C) Marte"), 1),
        Pregunta("¿Cuántos continentes hay en el mundo?", listOf("A) 5", "B) 6", "C) 7"), 2),
        Pregunta("¿En qué año llegó el hombre a la luna?", listOf("A) 1969", "B) 1970", "C) 1980"), 0),
        Pregunta("¿Cuál es el animal más rápido del mundo?", listOf("A) Guepardo", "B) Águila", "C) Halcón peregrino"), 2),
        Pregunta("¿Cuál es el océano más grande del mundo?", listOf("A) Atlántico", "B) Índico", "C) Pacífico"), 2),
        Pregunta("¿En qué país se originó el sushi?", listOf("A) China", "B) Japón", "C) Corea"), 1),
        Pregunta("¿Qué animal es conocido por su habilidad para cambiar de color?", listOf("A) Camaleón", "B) Serpiente", "C) Pavo real"), 0),
        Pregunta("¿Cuántos huesos tiene el cuerpo humano adulto?", listOf("A) 206", "B) 212", "C) 220"), 0),
        Pregunta("¿Qué instrumento musical tiene teclas negras y blancas?", listOf("A) Guitarra", "B) Piano", "C) Violín"), 1),
        Pregunta("¿Cuál es el continente más grande en términos de área?", listOf("A) África", "B) Asia", "C) Europa"), 1),
        Pregunta("¿En qué ciudad se encuentra la Torre Eiffel?", listOf("A) Londres", "B) París", "C) Roma"), 1),
        Pregunta("¿Quién fue el primer presidente de los Estados Unidos?", listOf("A) Abraham Lincoln", "B) George Washington", "C) Thomas Jefferson"), 1),
        Pregunta("¿Cuántos colores tiene el arco iris?", listOf("A) 6", "B) 7", "C) 8"), 1),
        Pregunta("¿Qué es más grande, la Tierra o la Luna?", listOf("A) Tierra", "B) Luna", "C) Son del mismo tamaño"), 0),
        Pregunta("¿Cuál es el animal marino más grande del mundo?", listOf("A) Ballena azul", "B) Tiburón ballena", "C) Orca"), 0),
        Pregunta("¿Qué país tiene más población del mundo?", listOf("A) India", "B) China", "C) Estados Unidos"), 1),
        Pregunta("¿Qué gas constituye la mayor parte de la atmósfera de la Tierra?", listOf("A) Oxígeno", "B) Nitrógeno", "C) Carbono"), 1),
        Pregunta("¿Cuántas horas tiene un día en la Tierra?", listOf("A) 12", "B) 24", "C) 18"), 1),
        Pregunta("¿Cuál es el metal más ligero?", listOf("A) Aluminio", "B) Hierro", "C) Litio"), 2),
        Pregunta("¿Qué país es conocido como 'la tierra del sol naciente'?", listOf("A) China", "B) Japón", "C) Corea"), 1),
        Pregunta("¿Qué deporte se juega con un balón esférico?", listOf("A) Béisbol", "B) Fútbol", "C) Rugby"), 1)
    )

    val curiosidadesMedio = listOf(
        Pregunta("¿En qué país se encuentra el famoso Machu Picchu?", listOf("A) Perú", "B) Bolivia", "C) Ecuador"), 0),
        Pregunta("¿Quién fue el autor de la teoría de la relatividad?", listOf("A) Isaac Newton", "B) Albert Einstein", "C) Galileo Galilei"), 1),
        Pregunta("¿Qué nombre recibe la línea imaginaria que divide la Tierra en dos hemisferios?", listOf("A) Ecuador", "B) Trópico de Cáncer", "C) Meridiano de Greenwich"), 0),
        Pregunta("¿Cuál es el metal más caro del mundo?", listOf("A) Oro", "B) Platino", "C) Rodio"), 2),
        Pregunta("¿Quién pintó la famosa obra 'La última cena'?", listOf("A) Pablo Picasso", "B) Leonardo da Vinci", "C) Vincent van Gogh"), 1),
        Pregunta("¿Qué animal tiene el cerebro más grande en relación con su tamaño corporal?", listOf("A) Delfín", "B) Elefante", "C) Serpiente"), 0),
        Pregunta("¿Cuál es el órgano más grande del cuerpo humano?", listOf("A) Corazón", "B) Hígado", "C) Piel"), 2),
        Pregunta("¿Qué planeta es conocido como el 'planeta rojo'?", listOf("A) Venus", "B) Marte", "C) Júpiter"), 1),
        Pregunta("¿Cuál es el río más largo del mundo?", listOf("A) Amazonas", "B) Nilo", "C) Yangtsé"), 1),
        Pregunta("¿En qué año se hundió el Titanic?", listOf("A) 1902", "B) 1912", "C) 1922"), 1),
        Pregunta("¿Qué científico desarrolló la teoría de la evolución?", listOf("A) Charles Darwin", "B) Gregor Mendel", "C) Nikola Tesla"), 0),
        Pregunta("¿Quién inventó la bombilla eléctrica?", listOf("A) Nikola Tesla", "B) Alexander Graham Bell", "C) Thomas Edison"), 2),
        Pregunta("¿Qué continente es hogar de los pingüinos?", listOf("A) África", "B) América del Sur", "C) Antártida"), 2),
        Pregunta("¿Qué gas es responsable del cambio climático?", listOf("A) Oxígeno", "B) Dióxido de carbono", "C) Nitrógeno"), 1),
        Pregunta("¿Qué tipo de animal es un delfín?", listOf("A) Reptil", "B) Mamífero", "C) Pez"), 1),
        Pregunta("¿Cuál es la moneda oficial de Japón?", listOf("A) Yen", "B) Won", "C) Yuan"), 0),
        Pregunta("¿Qué país es conocido por la Gran Muralla?", listOf("A) India", "B) China", "C) Corea del Sur"), 1),
        Pregunta("¿Cuál es el país más grande del mundo en términos de superficie?", listOf("A) Canadá", "B) Estados Unidos", "C) Rusia"), 2),
        Pregunta("¿Cuál es el continente más pequeño?", listOf("A) Oceanía", "B) Europa", "C) Antártida"), 0),
        Pregunta("¿Qué océano es el más pequeño?", listOf("A) Atlántico", "B) Índico", "C) Ártico"), 2),
        Pregunta("¿Cuál es el nombre del famoso volcán que destruyó Pompeya en el año 79 d.C.?", listOf("A) Etna", "B) Vesubio", "C) Krakatoa"), 1)
    )

    val curiosidadesAvanzado = listOf(
        Pregunta("¿En qué año se firmó la Declaración de Independencia de los Estados Unidos?", listOf("A) 1776", "B) 1789", "C) 1791"), 0),
        Pregunta("¿Cuál es la constante universal de gravitación?", listOf("A) 9.8 m/s²", "B) 6.674 × 10^-11 N·m²/kg²", "C) 3.14"), 1),
        Pregunta("¿Qué filósofo griego es conocido por su frase 'Conócete a ti mismo'?", listOf("A) Sócrates", "B) Platón", "C) Aristóteles"), 0),
        Pregunta("¿En qué siglo se desarrolló la teoría cuántica?", listOf("A) XIX", "B) XX", "C) XXI"), 1),
        Pregunta("¿Qué teoría afirma que el universo está en constante expansión?", listOf("A) Teoría de la relatividad", "B) Teoría del Big Bang", "C) Teoría de la gravedad cuántica"), 1),
        Pregunta("¿Qué es la antimateria?", listOf("A) Materia con propiedades opuestas a la materia normal", "B) Materia sin masa", "C) Materia visible en el espacio exterior"), 0),
        Pregunta("¿Cuál es el nombre del telescopio espacial lanzado por la NASA en 1990?", listOf("A) Hubble", "B) Kepler", "C) James Webb"), 0),
        Pregunta("¿Cuál es el proceso mediante el cual las plantas convierten la luz solar en energía?", listOf("A) Respiración celular", "B) Fotosíntesis", "C) Evaporación"), 1),
        Pregunta("¿Qué fórmula describe la ley de la gravitación universal?", listOf("A) F = ma", "B) F = G (m₁m₂/r²)", "C) E = mc²"), 1),
        Pregunta("¿Qué compuesto químico es responsable de la acidez del vinagre?", listOf("A) Ácido acético", "B) Ácido cítrico", "C) Ácido clorhídrico"), 0),
        Pregunta("¿Quién es considerado el padre de la geometría?", listOf("A) Euclides", "B) Pitágoras", "C) Arquímedes"), 0),
        Pregunta("¿En qué lugar se encuentra el mayor desierto del mundo?", listOf("A) África", "B) Antártida", "C) Asia"), 1),
        Pregunta("¿Cuál es el punto más bajo de la Tierra?", listOf("A) La fosa de las Marianas", "B) El Mar Muerto", "C) La cuenca del río Amazonas"), 1),
        Pregunta("¿Cuánto mide el radio de la Tierra?", listOf("A) 6,371 km", "B) 7,500 km", "C) 8,200 km"), 0),
        Pregunta("¿En qué año se descubrió la penicilina?", listOf("A) 1928", "B) 1914", "C) 1935"), 0),
        Pregunta("¿Cuál es la unidad básica de la vida?", listOf("A) Célula", "B) Átomo", "C) Molécula"), 0),
        Pregunta("¿Qué compuesto químico es el principal responsable de la capa de ozono?", listOf("A) CO₂", "B) O₃", "C) O₂"), 1),
        Pregunta("¿Quién fue el primer humano en viajar al espacio?", listOf("A) Neil Armstrong", "B) Yuri Gagarin", "C) John Glenn"), 1),
        Pregunta("¿Qué es el bosón de Higgs?", listOf("A) Una partícula subatómica", "B) Una estrella en la Vía Láctea", "C) Un tipo de energía"), 0),
        Pregunta("¿Cuál es la teoría que describe el comportamiento de los objetos en el espacio-tiempo?", listOf("A) Teoría de la relatividad", "B) Teoría cuántica", "C) Teoría de cuerdas"), 0)
    )
}
